### ISSUE TITLE
How to load by webpack

### ISSUE THREAD

**Issue by yssource** [inmagik/ionic-color-picker#3]
Nowadays, since webpack is very popular, and I wanna know it is supported by webpack?  If it' s,  how to use it with webpack?

**Comment by bianchimro** [comment]
@yssource I do not know webpack well, but I'll take a look at what is needed to integrate it.
If you have some pointers let me know

**Comment by yssource** [comment]
@bianchimro If I use this by "require" method to load the js file.  
like this ( I use the min. js)
            require('lib/ionic-color-picker/ionic-color-picker-tinycolor.min.js')
and them inject into my module 
            angular.module('starter', ['ionic', 'ionic-color-picker'])
As a result,  it always error logs with "tinycolor is not defined. " 

If I follow your ways by "<script src="lib/ionic-color-picker/ionic-color-picker.js"></script>" everything is OK. 
So,  it seems not working with require.

**Comment by yssource** [comment]
I fixed my problem which is caused by "shimming module" for webpack usage.
1. npm install exports-loader --save-dev
2. in webpack.config.js add resolve alias: {'ionic-color-picker', node_modules_dir + '/ionic-color-picker/dist/ionic-color-picker-tinycolor.min.js'}
3.  require('expose?tinycolor!ionic-color-picker');  --- here the prefix of "expose?tinycolor!" is very critical 

Finally,  maybe this will be helpful for someone if you'd like to use the plugin configured with webpack.

**Comment by bianchimro** [comment]
@yssource, thanks for reporting !

if you feel so, you could fork the project, add the needed config for webpack and make a pr.

I am not very expert with packaging, but probably tinycolor should never be bundled and specified properly as a dependency.

would this help for webpack ?

**Comment by yssource** [comment]
I think there is not necessarily to change any code with your projects.  Actually,  this is a problem about  how to use “shimming module” with webpack,  or requirejs.  
The tinycolor. js has already provided  the followings codes for Node and AMD.

<pre>
// Node: Export function
if (typeof module !== "undefined" && module.exports) {
    module.exports = tinycolor;
}
// AMD/requirejs: Define the module
else if (typeof define === 'function' && define.amd) {
    define(function () {return tinycolor;});
}
// Browser: Expose to window
else {
    window.tinycolor = tinycolor;
}
</pre>

Maybe,  the link would be helpful https://github.com/webpack/docs/wiki/shimming-modules

If the user wanna use your project with requirejs. 
 I think it would be like the following codes in the requirejs conifg file main.js 

<pre>
require.config({
  paths: {
      'ionic-color-picker': '/path/to/ionic-color-picker.min.js'
   },
  shim: {
      'ionic-color-picker': {
          deps: [
          'ionic'
          ],
          exports: 'tinycolor'
       }
  }
})
</pre>

Note, I do not test this with requirejs.

**Comment by bianchimro** [comment]
@yssource thanks for your response, sorry I picked it up just now.
I am closing this issue for now but If you feel so, please reopen it and submit a PR with a modified README, with a new section just after "examples" section.
