### ISSUE TITLE
color not initialized

### ISSUE THREAD

**Issue by arnaudlevallois** [inmagik/ionic-color-picker#5]
At the first color picker display, the color is black (all fields are set to 0) :
![color_picker_bug](https://cloud.githubusercontent.com/assets/15228244/12952844/475e1098-d018-11e5-9226-ece4b07875f1.png)

If I cancel and I click color again, color is ok : 
![color_picker](https://cloud.githubusercontent.com/assets/15228244/12952875/646480fa-d018-11e5-84ea-992512b95c42.png)

**Comment by bianchimro** [comment]
hi @arnaudlevallois,
thanks for reporting.

should be fixed in master, can you confirm?
if not, can you submit a codepen showing the issue

best regards

**Comment by arnaudlevallois** [comment]
hi @bianchimro,

I confirm that this is fixed in master.

Thank you for your fast response!

**Comment by bianchimro** [comment]
great!
